### PR TITLE
changed title of container talk

### PR DESCRIPTION
**Pull request by kara**

### CODE REVIEW

**Comment by geddski** [comment]
Thx Kara. Could you also update it in the schedule repo?

**Comment by kara** [comment]
This isn't the schedule repo?  Can you send me a link to it?

**Comment by geddski** [comment]
It is lol. I meant the submissions repo. We're going to link to that repo's data for a details page on the schedule.

**Comment by kara** [comment]
Oh okay, haha.  Here is the other PR:

https://github.com/ng-conf/submissions-2015/pull/198

**Pull request merged**
